services:
  attendees-quarkus:
    image: masteringapi/attendees-quarkus:ws-native-db
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conference
      POSTGRES_USER: calm
      POSTGRES_PASSWORD: demo